### ISSUE TITLE
GoTo on the right click user menu doesn't work!

### ISSUE THREAD

**Issue by badgamernl** [badgamernl/explosivegaming-main#50]
**Describe the bug**
GoTo on the right click user menu doesn't work!

**To Reproduce**
1. Open the 'Player list'
2. Right Click on a 'player'
3. Click on the 'GoTo' button
4. Doesn't work

**Expected behavior**
TP your player to selected player.

**Comment by Cooldude2606** [comment]
Correction the player list works, its the admin gui that does not; also fixed.
