### ISSUE TITLE
Death Marker here - then gone

### ISSUE THREAD

**Issue by aldldl** [badgamernl/explosivegaming-main#61]
**Describe the bug**
When I die the marker is only there for a short time. It seems to be about 30 seconds. When trying to find your body it disappears before you can fight the biters away.

**To Reproduce**
1. Get shanked by a biter
2. Wait on the ground as a corps
3. Get marked on the map as dead
4. Go run/walk to your body
5. marker disappears before you can get close

**Expected behavior**

Marker should not go away that quick.

**Screenshots**

**Other information (please complete the following information):**
 - OS: Windows
 - Factorio Version: 0.16.45

**Additional context**

**Comment by aldldl** [comment]
Update, I just killed myself - got a marker, after more than one min it disappeared. no one touched my body.

I killed myself again and got a marker, while looking at it on the map the script refreshed and it disappeared but my body in both cases are still there now.

**Comment by Cooldude2606** [comment]
The corpse is not yet made on the player death event which is when i was looking for it, now it will look for the corpse before removing the tag from the map. [See fix.](https://github.com/badgamernl/explosivegaming-main/commit/ffbe97186958f09ff084559826cbdee649109bc9)
